### PR TITLE
Remove unnecessary commented code

### PR DESCRIPTION
**Pull request by pushrax**

### CODE REVIEW

**Comment by agentzh** [comment]
@pushrax I'm fine with removing the commented local variable definitions, but not commented print() statements. Since I may want to uncomment them temporarily during debugging :)

**Comment by pushrax** [comment]
Sure, sounds good. I'll revise this PR.

**Comment by pushrax** [comment]
@agentzh updated

**Comment by agentzh** [comment]
Thanks!

**Pull request merged**
