### PR TITLE
feature: provide a way to reuse table in ngx.req.get_uri_args

### PR DESCRIPTION
**Pull request by spacewander**
TODO: add docs.

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-resty-core project.

### CODE REVIEW

**Comment by spacewander** [comment]
@doujiang24 
Updated.

**Comment by doujiang24** [comment]
@spacewander LGTM, we need the doc for this change as you have mentioned.

**Comment by spacewander** [comment]
@doujiang24 
I will write the doc in lua-nginx-module after this PR is merged.

**Comment by zhuizhuhaomeng** [comment]
@chronolaw  would you please rebase to the latest master ?

**Review by zhuizhuhaomeng — APPROVED** [review]

**Comment by zhuizhuhaomeng** [comment]
@spacewander  would you please rebase to the latest code and add the doc?

**Comment by spacewander** [comment]
Already done.

**Pull request merged**
