### PR TITLE
Feature balancer disable ssl

### PR DESCRIPTION
**Pull request by vislee**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-resty-core project.

ref: https://github.com/openresty/lua-nginx-module/pull/1687

### CODE REVIEW

**Comment by doujiang24** [comment]
@vislee thanks for your contribution.
`disable_ssl` is not a good idea, `set_upstream_ttl(enabled)` should be better, we can decide `http` or `https` per upstream try.

**Comment by vislee** [comment]
> @vislee thanks for your contribution.
> `disable_ssl` is not a good idea, `set_upstream_ttl(enabled)` should be better, we can decide `http` or `https` per upstream try.

@doujiang24  Yes, 'disable_ssl' is not accurate, but this feature relies on 'proxy_pass https://'. I'm concerned that 'set_upstream_ttl(enabled)' might be misused.

**Comment by doujiang24** [comment]
>  but this feature relies on 'proxy_pass https://'.
@vislee yeah, I knew it, we can only clarify it in the document.
I think `set_upstream_ttl` is better since we can support this usage:
```
set_upstream_tls(false) -- first try
set_upstream_tls(true) -- second try
```
maybe we should put this api to another new c module? like lua-conf-nginx-module. thoughts? @thibaultcha @spacewander @rainingmaster

**Comment by zhuizhuhaomeng** [comment]
I would like to bring to your attention that this feature has been rewritten and can be found in the following pull request URL: https://github.com/openresty/lua-resty-core/pull/460.

**Pull request closed without merging**
