### PR TITLE
feature: make os.getenv see env directives in init_by_lua.

### PR DESCRIPTION
**Pull request by thibaultcha**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-resty-core project.

Sister PR: https://github.com/openresty/lua-nginx-module/pull/1343

### CODE REVIEW

**Comment by hongliang5316** [comment]
@thibaultcha 
That's nothing, i need this feature.
Having multiple prs is a good thing:).

**Comment by thibaultcha** [comment]
Note: This is implemented in `misc.lua` but happy to move it to a new file if needed.

**Comment by thibaultcha** [comment]
Just realized: this needs to be ported to the meta-module and there needs to be `t/stream/os-getenv.t` tests as well. Otherwise this does not work in the stream module. Will do this next.

**Comment by thibaultcha** [comment]
PR is up for the meta-module: https://github.com/openresty/meta-lua-nginx-module/pull/55 and the `t/stream/os-getenv*.t` suites were added to this PR.

**Pull request merged**
