### PR TITLE
optimize: shdict: switched exptime argument type to 'long' to avoid potential overflows.

### PR DESCRIPTION
**Pull request by thibaultcha**
> I hereby granted the copyright of the changes in this pull request
to the authors of this lua-resty-core project.

Sister PR of https://github.com/openresty/lua-nginx-module/pull/1229

### CODE REVIEW

**Comment by thibaultcha** [comment]
@agentzh The Travis builds were really janky yesterday it seems, several PRs I sent didn't pass the CI for unrelated reasons. Hoping you get a chance to restart them :)

**Comment by membphis** [comment]
@spacewander has fixed this bug already: https://github.com/openresty/lua-resty-core/pull/171

it was not merged now.

**Comment by thibaultcha** [comment]
@membphis did you mean to link to another PR or am I overlooking something?

**Comment by membphis** [comment]
@thibaultcha you can ignore the error in travis build. it's fixed at another PR https://github.com/openresty/lua-resty-core/pull/171.

**Comment by thibaultcha** [comment]
Oh, sorry I thought you were talking about the PR itself! Ok! :D

**Comment by thibaultcha** [comment]
@membphis thanks for the note!

**Comment by thibaultcha** [comment]
@agentzh Ping here - let me know if you want to update those to `uint64` (I used `long` as per your suggestion [here](https://github.com/openresty/lua-nginx-module/pull/1226#discussion_r160292541))

**Comment by agentzh** [comment]
@thibaultcha Merged. Thanks!

**Pull request closed without merging**
