### PR TITLE
feature: ngx.balancer: added new API functions set_timeouts() for setting upstream timeouts

### PR DESCRIPTION
**Pull request by agentzh**
This supersedes #30.

### CODE REVIEW

**Comment by agentzh** [comment]
@xbsura @toruneko Please review this PR. Thanks!

**Comment by toruneko** [comment]
what happened？—— “All checks have failed”

**Comment by agentzh** [comment]
@toruneko Well, Travis CI only uses the git master branch of lua-nginx-module. That's why the checks are failing. You can see that from the Travis CI's detailed test report.

**Comment by agentzh** [comment]
@toruneko @xbsura FYI, I've just committed a change to git master that changes the timeout values' unit from millisecond to second while still preserving the ms precision:

https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#set_timeouts

This aligns up with the rest of API functions accepting timeout values (except for the cosocket API, which keeps compatible with LuaSocket's API by intention).

**Pull request merged**
