### PR TITLE
bugfix: remove redundant require in core.lua

### PR DESCRIPTION
**Pull request by chronolaw**
It seems there are some redundant code in core.lua

So I remove them, please check it, thanks.

### CODE REVIEW

**Comment by spacewander** [comment]
@chronolaw 
It would be great to sort the module to make the code easier to read.
If you do so, note that the regex module should be loaded first to inject `ngx.re` for other modules.

**Comment by chronolaw** [comment]
I'm sorry that I would not change the sequence of modules, because I am not familiar with all lua core modules.

And what is the easiest way to read? alphabet or other?

**Comment by spacewander** [comment]
It's OK. Whether to sort it or not is up to you.

**Comment by thibaultcha** [comment]
@chronolaw Thank you!

**Pull request merged**
